### ISSUE TITLE
Not able to get itemModBlacklist to Work

### ISSUE THREAD

**Issue by FallenEagle1** [Ipsis/Woot#380]
Modpack: All the Mods 3 ptr 2
Forge: 14.23.4.2756
Woot: 1.12.2-1.4.2

This might be something that I'm missing to put in into the config, but I'm not able to get the itemmodblacklist to work for ElectroBob's Wizardry. Trying to stop the acquisition of the spell books through a woot farm, so I'm just trying to blacklist the mod in general (there are a lot of books). Here is the snippet of config that pertains to it, from the factory_config.json
```  "entitywhitelist": [  ],
  "itemmodblacklist": [ 
	"ebwizardry"
  ],
  "itemblacklist": [  ]
}
```
Attached is the json file (as a text) if you wanted to see it. I can grab the log file as well, but I looked through it to see if there was an error for woot about it, but wasn't seeing one.

[factory_config.txt](https://github.com/Ipsis/Woot/files/2311454/factory_config.txt)

**Comment by Ipsis** [comment]
I may have forgotten to actually implement the canDrop/canLearn methods that handle the item policy. Entities are all fine, it is just the item ones that are missing.

I'll get that hooked up and release a new version.

**Comment by Ipsis** [comment]
b53d585880eaafa7eb86a7a2158775efe674c401

Example usage:

```
 "itemmodblacklist": [
    "actuallyadditions"
  ],
  "itemblacklist": [
    {
      "item": "minecraft:gunpowder"
    }
  ]
```

This will block items from being learned and block already learned items from being dropped.
Blacklisted items will not show up in the gui or in the "TOP" overlay

**Comment by FallenEagle1** [comment]
Thanks! Just waiting on the next release now :D

**Comment by Ipsis** [comment]
I've pushed the 1.4.4 update so you should see it tomorrow - Curse can be a little slow at the weekend.

**Comment by Yamza** [comment]
It seems this is still not working properly. In addition, the config for the extra shard drops is not stopping shards from dropping. 

Woot: https://hatebin.com/gbupbehgiw
Factory Config: https://hatebin.com/iedabnhibq
Factory Config2: https://hatebin.com/uctfuypwcm
Factory Config3: https://hatebin.com/uwnoqkkfrg

Items dropping: https://i.imgur.com/kUFoZRI.png

**Comment by Ipsis** [comment]
Sorry @Yamza , completely missed that this issue had been updated.
For the shard "B:allowShardRecipe=false" will disable the shard recipe and also the generation of the shards.
<edited>

I ran your config file and the answer is that some of the tomstone items required metadata to be specific.

So you can either use the below to blacklist all the drops from that mod
"itemmodblacklist": [ "tombstone"] 

or
The following to blacklist the specified drops

```json
  "itemblacklist": [
    {
      "item": "tombstone:scroll_buff",
      "data": 0
    },
    {
      "item": "tombstone:scroll_buff",
      "data": 1
    },
    {
      "item": "tombstone:scroll_buff",
      "data": 2
    },
    {
      "item": "tombstone:scroll_buff",
      "data": 3
    },
    {
      "item": "tombstone:scroll_buff",
      "data": 4
    },
    { "item": "tombstone:voodoo_poppet" },
    { "item": "tombstone:soul_receptacle" }
  ],
```

**Comment by Yamza** [comment]
Ah I see. Thank you!
