### ISSUE TITLE
Cant Export update using woot-1.16.4-1.0.3.1.jar

### ISSUE THREAD

**Issue by IchigoGames** [Ipsis/Woot#500]
if you look at game version version 1.0.3.1 just says Forge this is preventing it from exporting when updating modpack in case you where wondering this is most likely why that version has less downloads.
![image](https://user-images.githubusercontent.com/11888162/107112704-26d99280-681f-11eb-9356-76ca28b921c0.png)

**Comment by IchigoGames** [comment]
what i mean by cant is if you try using that version it will add it to mods folder and as its a mod all ready on curse it will get the modpack update rejected

**Comment by Ipsis** [comment]
Thanks.
I had a look at the page and for the 1.0.3.1 I had only selected Forge/1.16.4 where I usually do Forge/1.16.4/1.16.3.
I've fixed that now.

**Comment by IchigoGames** [comment]
![image](https://user-images.githubusercontent.com/11888162/107129590-0e539180-688c-11eb-9073-74de575f59eb.png)
darn i was sure that was the issue

**Comment by IchigoGames** [comment]
but it still wont allow that version to be included thinks its not on curse so adds it to mods folder so i wont be able to use it.

**Comment by IchigoGames** [comment]
hopefully ill have better luck the next update that comes out.

**Comment by Ipsis** [comment]
I just did a test export from CurseForge with "Better Advancement/JEI/Woot-1.0.3.1"
The overrides directory only includes the config directory for me and no mods.
I'm not too familiar with how CurseForge works.

**Comment by IchigoGames** [comment]
i think its because im exporting in a 1.16.5 mc odd that it works with woot 1.0.3.0 tho but not Woot-1.0.3.1"

**Comment by Ipsis** [comment]
Latest Woot was released for 1.16.5, which will be the base version for the mod.
